kind: ConfigMap
apiVersion: v1
metadata:
  name: py-script-map
  namespace: pyfarm
immutable: false
data:
  spark-job-access-gcs.py: |
    import pyspark 
    import sys
    
    BUCKET = "tech_sandbox-corp-pyfarm-dev-b16e"
    inputUri=f"gs://{BUCKET}/123/test-file.txt" outputUri=f"gs://{BUCKET}/test_file_output"
    sc = pyspark.SparkContext
    lines = sc.textFile(inputUri)
    words = lines.flatMap(lambda line: line.split)
    wordCounts = words.map(lambda word: (word, 1)).reduceByKey(Lambda counti, count2: counti + count2) 
    wordCounts.saveAsTextFile(outputUri)
