---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - name: test-container
      image: google/cloud-sdk:alpine
      command: [ "/bin/sh","-c","top" ]
      volumeMounts:
      - name: py-script-vol
        mountPath: /opt
      - name: key-vol
        mountPath: /mnt
  volumes:
  - name: py-script-vol
    configMap:
      name: py-script-map
      items:
        - key: spark-job-access-gcs.py
          path: spark-job-access-gcs.py
  - name: key-vol
    secret:
      secretName: gcs-bq
      items:
        - key: comp.json
          path: key.json
    
    
  restartPolicy: Never
