---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: pyfarm
spec:
  containers:
    - name: test-container
      #image: gcr.io/google_containers/busybox
      #image: gcr.io/ynli-k8s/spark:v2.3.0-gcs # - can`t download
      image: google/cloud-sdk:alpine
      command: [ "/bin/sh","-c","cat /opt/spark-job-access-gcs.py" ]
      volumeMounts:
      - name: py-script-vol
        mountPath: /opt
      - name: key-vol
        mountPath: /mnt
  volumes:
  - name: py-script-vol
    configMap:
      name: py-script-map
      items:
        - key: spark-job-access-gcs.py
          path: spark-job-access-gcs.py
  - name: key-vol
    secret:
      secretName: gcs-bq
      items:
        - key: comp.json
          path: key.json
    
    
  restartPolicy: Never
